apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: ui_approach/nginx
    repoURL: https://github.com/rajcharanthecoder/argocd-demos.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
